// utils/planets.js

const planets = [
  {
    name: "Mercury",
    radius: 0.5,
    distance: 10,
    speed: 0.01,
    texture: "/textures/2k_mercury.jpg",
    moons: [],
    eccentricity: 0.205,
    orbitColor: 0xffa500,
     orbitOpacity: 0.02,
    glowColor: "orange",
    glowPulseColor: "#ffcc80",
    axialTilt: 0.01,
  },
  {
    name: "Venus",
    radius: 0.8,
    distance: 15,
    speed: 0.007,
    texture: "/textures/2k_venus_surface.jpg",
    moons: [],
    eccentricity: 0.007,
    orbitColor: 0xffc0cb,
     orbitOpacity: 0.02,
    glowColor: "pink",
    glowPulseColor: "#ff99bb",
    axialTilt: 177.4,
  },
  {
    name: "Earth",
    radius: 1,
    distance: 20,
    speed: 0.005,
    texture: "/textures/2k_earth_daymap.jpg",
    moons: [{ name: "Moon", radius: 0.3, distance: 3, speed: 0.015 }],
    eccentricity: 0.017,
    orbitColor: 0x3399ff,
     orbitOpacity: 0.02,
    glowColor: "cyan",
    glowPulseColor: "#00ffff",
    axialTilt: 23.44,
  },
  {
    name: "Mars",
    radius: 0.7,
    distance: 30,
    speed: 0.003,
    texture: "/textures/2k_mars.jpg",
    moons: [
      { name: "Phobos", radius: 0.1, distance: 2, speed: 0.02 },
      { name: "Deimos", radius: 0.2, distance: 3, speed: 0.015 },
    ],
    eccentricity: 0.093,
    orbitColor: 0xff4500,
     orbitOpacity: 0.02,
    glowColor: "red",
    glowPulseColor: "#ff6666",
    axialTilt: 25.19,
  },
  {
    name: "Jupiter",
    radius: 1.8,
    distance: 38,
    speed: 0.0025,
    texture: "/textures/2k_mars.jpg",
    moons: [],
    eccentricity: 0.048,
    orbitColor: 0xffd27f,
     orbitOpacity: 0.02,
    glowColor: "orange",
    glowPulseColor: "#ffbb66",
    axialTilt: 3.13,
  },
  {
    name: "Saturn",
    radius: 2.5,
    distance: 48,
    speed: 0.002,
    texture: "/textures/2k_mars.jpg",
    moons: [],
    eccentricity: 0.056,
    orbitColor: 0xffff99,
     orbitOpacity: 0.02,
    glowColor: "yellow",
    glowPulseColor: "#ffffcc",
    axialTilt: 26.7,
    rings: {
      innerRadius: 3,
      outerRadius: 4,
      // texture: "/textures/2k_moon.png", // not used for now
    },
  },
  {
    name: "Uranus",
    radius: 2.1,
    distance: 58,
    speed: 0.0018,
    texture: "/textures/2k_venus_surface.jpg",
    moons: [],
    eccentricity: 0.047,
    orbitColor: 0x66ccff,
     orbitOpacity: 0.02,
    glowColor: "lightblue",
    glowPulseColor: "#99ddff",
    axialTilt: 97.77,
  },
  {
    name: "Neptune",
    radius: 2,
    distance: 68,
    speed: 0.0016,
    texture: "/textures/2k_earth_daymap.jpg",
    moons: [],
    eccentricity: 0.009,
    orbitColor: 0x3366ff,
    orbitOpacity: 0.02,
    glowColor: "blue",
    glowPulseColor: "#6699ff",
    axialTilt: 28.32,
  },
];

export default planets;
